### ISSUE TITLE
MySQL Router 8.0.22 enables REST API

### ISSUE THREAD

**Issue by lefred** [hmatsu47/mysql80_no_usui_hon#50]
in 8.0.22 now the REST API is enabled by default (improvement since 8.0.17). You have more info on https://lefred.be/content/mysql-router-8-0-22-enables-rest-api-at-bootstrap/

Cheers !

**Comment by hmatsu47** [comment]
Thanks for the new URL. I've updated it!

---

**HTTP サーバプラグインとREST API**
 * https://lefred.be/content/mysql-router-8-0-22-enables-rest-api-at-bootstrap/
   * 8.0.17で追加、8.0.22でデフォルト有効に
